"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
- Triangle T_n = n(n + 1)/2
- Pentagonal P_n = n(3n - 1)/2 	
- Hexagonal H_n = n(2n - 1)

It can be verified that T_285 = P_165 = H_143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""

def valid(number: int) -> bool:

    # Triangle
    t = (-1 + (1 + 8*number)**0.5) / 2
    # Pentagonal
    p = (1 + (1 + 24*number)**0.5) / 6
    # Hexagonal
    h = (1 + (1 + 8*number)**0.5) / 2
    
    return t == int(t) and p == int(p) and h == int(h)

# Must be an odd numebr
lower_limit = 1500000001
upper_limit = 1533776806

for i in range(lower_limit, upper_limit, 2):
    if valid(i):
        print(i)
