"""
How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100 and 2 <= b <= 100?
"""

lower_limit = 2
upper_limit = 100

values = set()

for i in range(lower_limit, upper_limit + 1):
    for j in range(lower_limit, upper_limit + 1):
        values.add(i**j)

answer = len(values)
print(answer)